config/routes.rb
Rails.application.routes.draw do
  resources :parties
  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'features' => 'home#features'
  root 'home#index'

end

app/models/party.rb
class Party < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pagename = 'Home';
  end
  def about
    @pagename = 'About';
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  def makeURL
    return (0...8).map { (65 + rand(26)).chr }.join
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create

    @party = Party.new(party_params)
    @party.URL = makeURL
    respond_to do |format|
      if @party.save && verify_recaptcha(:model => @party, :message => "Oh! It's error with reCAPTCHA!")
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
    path = "/app/views/parties/" + @party.URL + ".html"
    content = "this random page works"
    File.open(path, "w+") do |f|
      f.write(content)
    end



  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
   end
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:Name, :Date, :Location, :Requirements, :Password, :URL, :Token)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def titlehelper(pagename)
    return 'LanCore' if pagename === 'Home'
    return 'LanCore' if pagename === nil
    pagename+' - LanCore'
  end

  def footerhelper(pagename)
    return 'margin-top: 0;' if pagename === 'Home'
    ''
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/dashboard/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center orange-text">Dashboard</h1>
    <div class="row center">
      <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
    </div>
    <div class="row center">
      <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
    </div>
    <br><br>

  </div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>
    </div>

  </div>
  <br><br>

  <div class="section">

  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  In Progress
</div>

app/views/home/features.html.erb
<div class="container">
  In Progress
</div>

app/views/home/index.html.erb
<div id="image-wrapper" class="valign-wrapper">
  <div id="homecontent" class="home-headline center white-text">
    <br>

    <div class="container">
      <div class="card-panel purple">
        <a href="<%= root_path %>" class="center hide-on-large-only"><img class="hero-logo" src="<%= path_to_image('logo.png') %>"></a>

        <h1>We can host your LAN party</h1>

        <h2><i>no matter the size!</i></h2>
        <br>

        <p class="flow-text">LanCore is a free, open source platform for hosting your LAN party. No sign-ups or logins
          required, just setup your party, send a link and token to the attendees, and have fun!</p>
        <br>
        <%= link_to "Start your party!", new_party_path, class: 'waves-effect waves-light btn-large col s6'%>
        <br><br>
      </div>
    </div>
  </div>
  <img class="hide-on-small-only home-img" src="<%= path_to_image('dreamhack2004landscape.jpg') %>">
  <img class="hide-on-med-and-up home-img" src="<%= path_to_image('dreamhack2004portrait.jpg') %>">
</div>
<!-- Image Layout JQuery -->
<script>
    $(document).ready(function () {
        var $window = $(window);
        var homeImage = $('#image-wrapper');
        var navWrapper = $('.nav-wrapper');
        var footer = $('.page-footer');
        var content = $('#homecontent');

        function checkWidth() {
            var viewportHeight = $window.height() - navWrapper.height() - footer.height() - 20;
            var contentHeight = content.height();
            if (viewportHeight > contentHeight) homeImage.height(viewportHeight);
            else homeImage.height(contentHeight);
        }

        checkWidth();
        $(window).resize(checkWidth);
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="msapplication-tap-highlight" content="no">
  <meta name="description" content="LanCore is a completely free and open source platform for hosting LAN parties, large and small.">
  <title><%= titlehelper(@pagename) %></title>
  <!-- Favicons -->
  <link rel="apple-touch-icon" sizes="57x57" href="<%= path_to_image('apple-icon-57x57.png') %>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%= path_to_image('touch-icon-iphone.png') %>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%= path_to_image('apple-icon-72x72.png') %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= path_to_image('touch-icon-ipad.png') %>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%= path_to_image('apple-icon-114x114.png') %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= path_to_image('touch-icon-iphone-retina.png') %>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%= path_to_image('apple-icon-144x144.png') %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= path_to_image('touch-icon-ipad-retina.png') %>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%= path_to_image('apple-icon-180x180.png') %>">
  <meta name="msapplication-TileColor" content="#ba68c8">
  <meta name="msapplication-TileImage" content="<%= path_to_image('mstile-144x144.png') %>">
  <link rel="shortcut icon" href="<%= path_to_image('favicon.ico') %>">
  <link rel="icon" href="<%= path_to_image('favicon.ico') %>">
  <link rel="icon" href="<%= path_to_image('favicon-16.png') %>" sizes="16x16">
  <link rel="icon" href="<%= path_to_image('favicon-32.png') %>" sizes="32x32">
  <link rel="icon" href="<%= path_to_image('favicon-48.png') %>" sizes="48x48">
  <link rel="icon" href="<%= path_to_image('favicon-64.png') %>" sizes="64x64">
  <link rel="icon" href="<%= path_to_image('favicon-128.png') %>" sizes="128x128">
  <!--  Android 5 Chrome Color -->
  <meta name="theme-color" content="#ba68c8">
  <!-- iOS Status Bar Color -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#ba68c8">
  <!-- CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- JS -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- CSRF -->
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <a href="#" class="brand-logo center hide-on-med-and-down"><img class="desktop-navbar-logo" src="<%= path_to_image('logo.png') %>"></a>
      <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <li><%= link_to "Features", features_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>
    <ul class="side-nav" id="mobile">
      <li>
        <a href="<%= root_path %>" class="center sidenav-header"><img class="responsive-img" src="<%= path_to_image('logo.png') %>"></a>
      </li>
      <li><%= link_to "Features", features_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </div>
</nav>
<%= yield %>
<footer class="page-footer" style="<%= footerhelper(@pagename) %>">
  <div class="footer-copyright">
    <div class="container">
      <span class="left">Made by <a class="blue-text text-lighten-3" href="http://mishaprasolov.com">Misha Prasolov</a> and
      <a class="blue-text text-lighten-3" href="https://github.com/amd1250x">Aaron D'Sa</a></span>
      <span class="right">
        <a class="white-text" href="https://github.com/LanCoreTeam"><i class="fa fa-github"></i></a>
        <a class="white-text" href="https://twitter.com/lan_core"><i class="fa fa-twitter"></i></a>
        <a class="white-text" href="#"><i class="fa fa-envelope"></i></a>
      </span>
    </div>
  </div>
</footer>
<!-- Google Analytics -->
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-9486909-21', 'auto');
    ga('send', 'pageview');

</script>
</body>
<!-- Navbar JQuery -->
<script>
    $(document).ready(function () {
        $('.button-collapse').sideNav({
                    edge: 'left',
                    closeOnClick: true
                }
        );
    });
</script>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <div class="container">
        <div class="card-panel amber darken-3 errorizer">
          <b><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</b>
          <ul>
            <% @party.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
    <div class="container">
      <div class="row">
        <div class="col s6">
          <div class="input-field">
            <%= f.label :Name %>
            <%= f.text_field :Name %>
          </div>
          <div class="input-field">
            <%= f.label :Date %>
            <%= f.text_field :Date, class: 'datepicker' %>
          </div>
          <div class="input-field">
            <%= f.label :Location %>
            <%= f.text_field :Location %>
          </div>
          <div class="input-field">
            <%= f.label :Password %>
            <%= f.password_field :Password %>
          </div>
          <div class="input-field">
            <%= f.label :Token %>
            <%= f.text_field :Token %>
          </div>
          <div class="container">
            <%= recaptcha_tags %>
          </div>
          <br>
          <div class="row">
            <div class="col s6">
              <%= link_to "Back", home_path, class: 'waves-effect waves-light btn' %>
            </div>
            <div class="col s6">
              <%= f.button :submit => "", class: 'waves-effect waves-light btn' %>
            </div>
          </div>
        </div>
        <div class="col s6">
            <div class="row">
              <img style="height:150px; display:block; margin-left:auto; margin-right:auto;" src = <%= path_to_image('logo.png') %> >
            </div>
            <br>
            <div class="row">
              <h2><i></i></h2>
            </div>
        </div>
      </div>

    </div>


<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Requirements</th>
      <th>Password</th>
      <th>Url</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.Name %></td>
        <td><%= party.Date %></td>
        <td><%= party.Location %></td>
        <td><%= party.Requirements %></td>
        <td><%= party.Password %></td>
        <td><%= party.URL %></td>
        <td><%= party.Token %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<br>
<div class="container">
  <div class="head-title z-depth-1">New Party</div>
</div>
<br>


<%= render 'form' %>

<hr>
<script>
    $(document).ready(function () {
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15 // Creates a dropdown of 15 years to control year
        });
    });
</script>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.Name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @party.Date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @party.Location %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @party.Requirements %>
</p>

<p>
  <strong>Password:</strong>
  <%= @party.Password %>
</p>

<p>
  <strong>Url:</strong>
  <%= @party.URL %>
</p>

<p>
  <strong>Token:</strong>
  <%= @party.Token %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>